data <- read.table("household_power_consumption.txt",sep = ";", header = TRUE,stringsAsFactors = FALSE)
data[,"Date"]= as.Date(data[,"Date"], format = "%d/%m/%Y")
my_data <- subset (data, Date == "2007-02-01"| Date =="2007-02-02")
datatime <- strptime(paste(my_data[,"Date"], my_data[,"Time"], sep = " "), format = "%Y-%m-%d %H:%M:%S")
GlobalAP <-as.numeric(my_data$Global_active_power)
library(dplyr)
submeter <-select(my_data, Sub_metering_1 : Sub_metering_3) 
submeter[,"Sub_metering_1"] <-as.numeric(submeter$Sub_metering_1)
submeter[,"Sub_metering_2"] <-as.numeric(submeter$Sub_metering_2)
submeter[,"Sub_metering_3"] <-as.numeric(submeter$Sub_metering_3)
Vol <- as.numeric(my_data$Voltage)
Globalrp <- as.numeric(my_data$Global_reactive_power)
png("plot4.png", width = 480, height = 480)
par(mfcol = c(2,2))
plot(datatime, GlobalAP, type = "l", xlab = " ", ylab = "Global Active Power (kilowattes)")
plot(datatime, submeter$Sub_metering_1, col = "black",
     type = "l", xlab = " ", ylab = "Energy sub metering")
lines(datatime, submeter$Sub_metering_2, col = "red")
lines(datatime, submeter$Sub_metering_3, col = "blue")
legend("topright", legend = c("sub_metering_1","sub_metering_2","sub_metering_3"), lty = 1, col = c("black","red","blue"))
plot(datatime, Vol, type = "l")
plot(datatime, Globalrp, type = "l")
dev.off()