data <- read.csv("household_power_consumption.txt",sep = ";", header = TRUE,stringsAsFactors = FALSE")
data[,"Date"]= as.Date(data[,"Date"], format = "%Y-%m%-%d")
my_data <- subset (data, Date == "2007-02-01"| Date =="2007-02-02")
datatime <- strptime(paste(my_data[,"Date"], my_data[,"Time"], sep = " "), format = "%Y-%m-%d %H:%M:%S")
library(dplyr)
submeter <-select(my_data, Sub_metering_1 : Sub_metering_3) 
submeter[,"Sub_metering_1"] <-as.numeric(submeter$Sub_metering_1)
submeter[,"Sub_metering_2"] <-as.numeric(submeter$Sub_metering_2)
submeter[,"Sub_metering_3"] <-as.numeric(submeter$Sub_metering_3)
png("plot3.png", width = 480, height = 480)
plot(datatime, submeter$Sub_metering_1, col = "black",
type = "l", xlab = " ", ylab = "Energy sub metering")
lines(datatime, submeter$Sub_metering_2, col = "red")
lines(datatime, submeter$Sub_metering_3, col = "blue")
dev.off()